import { Service, Characteristic, type WithUUID, type CharacteristicValue } from 'homebridge';
import { PlatformAccessory } from 'homebridge';
import camelcase from 'camelcase';
import type { InterfaceForService } from './types/index.js';
import type { CamelCase, PascalCase } from 'type-fest';
import { FluentCharacteristic } from './FluentCharacteristic.js';
import { ValidationError } from './errors.js';
import { isService } from './type-guards.js';
import { getLogger } from './logger.js';

/**
 * Strongly-typed, fluent view of a HAP service and all its characteristics.
 *
 * @remarks
 * `FluentService<T>` is an intersection of the generated HAP interface for
 * service `T` and a set of helper methods (`onGet`, `onSet`, `update`) plus a
 * `characteristics` map of {@link FluentCharacteristic} instances keyed by
 * camelCase characteristic name.
 *
 * Shorthand property accessors (both camelCase `on` and PascalCase `On`) are
 * defined at runtime via `Object.defineProperty` so that TypeScript infers the
 * correct value type from the service interface.
 *
 * The type parameter `T` must be a HAP service constructor with an `interface`
 * declaration (generated by `hap-codegen`). Without the generated interface,
 * `InterfaceForService<T>` resolves to `never` and the type collapses.
 *
 * @typeParam T - HAP service class constructor (e.g., `typeof hap.Service.Lightbulb`).
 *
 * @useWhen
 * - You are building a Homebridge plugin that wraps one or more HAP services.
 * - You want compile-time IntelliSense on characteristic names and their value
 *   types (booleans, numbers, strings) for a specific service.
 * - You need to register `onGet`/`onSet` handlers or update characteristic
 *   values without manually typing characteristic display names.
 *
 * @avoidWhen
 * - You need direct hap-nodejs `Service` access (e.g., `service.getCharacteristic()`,
 *   `service.setPrimaryService(true)`) — `FluentService` does not expose all
 *   service methods; obtain the raw service via `platformAccessory.getService()`.
 * - Your accessory has a single, trivial characteristic — `hap-nodejs` directly
 *   may be simpler and incurs no overhead.
 *
 * @pitfalls
 * - NEVER register the same characteristic handler twice on the same service —
 *   hap-nodejs silently replaces the first handler, causing the original logic
 *   to be permanently dropped with no runtime error.
 * - NEVER mutate `characteristics` after `platformAccessory` has been published
 *   via `api.registerPlatformAccessories()` — hap-nodejs caches the service
 *   state at publish time; post-publish structural changes cause a silent desync
 *   with the iOS Home controller.
 * - NEVER assume `characteristics` contains characteristics that were not
 *   present on the service when `wrapService()` was called — optional HAP
 *   characteristics must be added to the service before wrapping.
 * - NEVER mix PascalCase and camelCase for the same characteristic in one
 *   handler registration call — the shorthand properties are aliases; prefer
 *   consistent camelCase to avoid confusion.
 *
 * @example
 * ```typescript
 * import { getOrAddService } from 'hap-fluent';
 *
 * const lightbulb = getOrAddService(accessory, hap.Service.Lightbulb, 'Living Room');
 *
 * // Register HomeKit GET/SET handlers
 * lightbulb.onGet('on', async () => await getLightState());
 * lightbulb.onSet('on', async (value) => await setLightState(value));
 *
 * // Programmatic update (no SET handler triggered, notifies HomeKit)
 * lightbulb.update('brightness', 75);
 *
 * // Shorthand property access
 * lightbulb.on = false;
 * const brightness = lightbulb.brightness; // number
 * ```
 *
 * @category FluentService
 */
export type FluentService<T extends typeof Service> = InterfaceForService<T> & {
  /**
   * Collection of all characteristics for this service
   * Keys are camelCase characteristic names (e.g., 'on', 'brightness')
   */
  characteristics: {
    [K in CharacteristicNamesOf<T> as CamelCase<K>]: FluentCharacteristic<
      InterfaceForService<T>[K] & CharacteristicValue
    >;
  };
  /**
   * Register an async getter for a characteristic
   *
   * @param key - Characteristic name (camelCase)
   * @param callback - Async function returning the characteristic value
   *
   * @example
   * ```typescript
   * service.onGet('on', async () => {
   *   const state = await getDeviceState();
   *   return state.isOn;
   * });
   * ```
   */
  onGet<K extends CharacteristicNamesOf<T>>(
    key: CamelCase<K>,
    callback: () => Promise<InterfaceForService<T>[K]>
  ): void;
  /**
   * Register an async setter for a characteristic
   *
   * @param key - Characteristic name (camelCase)
   * @param callback - Async function receiving the new value
   *
   * @example
   * ```typescript
   * service.onSet('on', async (value) => {
   *   await setDeviceState({ isOn: value });
   * });
   * ```
   */
  onSet<K extends CharacteristicNamesOf<T>>(
    key: CamelCase<K>,
    callback: (value: InterfaceForService<T>[K]) => Promise<void>
  ): void;
  /**
   * Update a characteristic value without triggering SET handlers
   *
   * @param key - Characteristic name (camelCase)
   * @param value - New characteristic value
   *
   * @example
   * ```typescript
   * // Update brightness from external state change
   * service.update('brightness', newBrightness);
   * ```
   */
  update<K extends CharacteristicNamesOf<T>>(
    key: CamelCase<K>,
    value: InterfaceForService<T>[K]
  ): void;
};

export type CharacteristicNamesOf<T extends typeof Service> = keyof Omit<
  InterfaceForService<T>,
  'UUID' | 'serviceName'
>;

/**
 * Retrieve an existing service from an accessory, or create and attach a new one,
 * then wrap it with the fluent helper interface.
 *
 * @remarks
 * This is the primary entry-point for working with HAP services in hap-fluent.
 * It calls `platformAccessory.getServiceById()` (when `subType` is provided)
 * or `platformAccessory.getService()` first, and only instantiates a new
 * service when none is found. The newly-created service is immediately added to
 * the accessory via `platformAccessory.addService()`.
 *
 * Use `subType` to differentiate multiple instances of the same service class
 * (e.g., two `Outlet` services on a power strip). The subtype string must be
 * stable across plugin restarts — HomeKit uses it to track the same logical
 * service across accessory cache refreshes.
 *
 * @param platformAccessory - Homebridge `PlatformAccessory` that owns the service.
 * @param serviceClass - HAP service constructor with a UUID (e.g., `hap.Service.Lightbulb`).
 * @param displayName - Human-readable name shown in the Home app for this service.
 * @param subType - Optional stable identifier for disambiguating multiple services
 *   of the same class on the same accessory.
 * @returns A {@link FluentService} wrapping the retrieved or newly-created service.
 *
 * @throws {Error} If `serviceClass` is not a constructor or lacks a `UUID` property.
 *
 * @useWhen
 * - Adding a service to an accessory in your plugin's constructor or
 *   `configureAccessory()` method.
 * - Idempotently initializing a service that may already exist in the cached
 *   accessory state across Homebridge restarts.
 *
 * @avoidWhen
 * - You already hold a raw `Service` instance — use {@link wrapService} directly
 *   to avoid the extra lookup overhead.
 *
 * @pitfalls
 * - NEVER call `getOrAddService()` after the accessory has been published via
 *   `api.registerPlatformAccessories()` — adding services post-publish results
 *   in the new service being invisible to the iOS Home controller until the next
 *   full accessory cache eviction (which requires the user to remove and
 *   re-add the accessory).
 * - NEVER use a dynamic or session-based `subType` — the subtype must be the
 *   same string on every Homebridge startup or HomeKit will treat the service
 *   as a new, duplicate service and duplicate entries appear in the Home app.
 *
 * @example
 * ```typescript
 * import { getOrAddService } from 'hap-fluent';
 *
 * // Single service
 * const lightbulb = getOrAddService(accessory, hap.Service.Lightbulb, 'Ceiling Light');
 *
 * // Multiple outlets on a power strip, differentiated by subType
 * const outlet1 = getOrAddService(accessory, hap.Service.Outlet, 'Left Outlet', 'outlet-1');
 * const outlet2 = getOrAddService(accessory, hap.Service.Outlet, 'Right Outlet', 'outlet-2');
 * ```
 *
 * @category FluentService
 */
export function getOrAddService<T extends typeof Service>(
  platformAccessory: PlatformAccessory,
  serviceClass: WithUUID<T>,
  displayName?: string,
  subType?: string
): FluentService<T> {
  const logger = getLogger();

  if (typeof serviceClass !== 'function') {
    logger.error({ serviceClass }, 'Service class must be a constructor function');
    throw new Error('Service class must be a constructor function');
  }
  if (!('UUID' in serviceClass)) {
    logger.error({ serviceClass }, 'Service class must have a UUID property');
    throw new Error('Service class must have a UUID property');
  }

  const existingService = subType
    ? platformAccessory.getServiceById(serviceClass, subType)
    : platformAccessory.getService(serviceClass);

  if (existingService) {
    logger.debug({ displayName, subType, uuid: serviceClass.UUID }, 'Found existing service');
    return wrapService(existingService as InstanceType<T>);
  } else {
    logger.debug({ displayName, subType, uuid: serviceClass.UUID }, 'Creating new service');
    const newService = new serviceClass(displayName ?? '', subType ?? '') as InstanceType<T>;
    platformAccessory.addService(newService);

    logger.info(
      {
        displayName,
        subType,
        uuid: serviceClass.UUID,
        characteristicCount: newService.characteristics.length
      },
      'Created and added new service'
    );

    return wrapService(newService);
  }
}

/**
 * Wrap an existing HAP `Service` instance with the fluent helper interface.
 *
 * @remarks
 * `wrapService` builds a {@link FluentService} around a service that was
 * obtained externally (e.g., from `platformAccessory.getService()` or created
 * manually). It iterates `service.characteristics` at call time and creates one
 * {@link FluentCharacteristic} per characteristic, keyed by camelCase display name.
 *
 * Characteristics added to the service **after** this call will not appear in
 * `.characteristics` — call `wrapService` again to refresh the map, or add
 * optional characteristics to the service before wrapping.
 *
 * @param service - A valid hap-nodejs `Service` instance to wrap.
 * @returns A {@link FluentService} providing typed `.characteristics`, `.onGet()`,
 *   `.onSet()`, `.update()`, and shorthand property accessors.
 *
 * @throws {ValidationError} If `service` does not satisfy the `isService()` type guard
 *   (i.e., is missing `UUID`, `displayName`, `getCharacteristic`, or `addCharacteristic`).
 *
 * @useWhen
 * - You already hold a raw `Service` instance (e.g., obtained via `platformAccessory.services`
 *   during `configureAccessory()`) and want the fluent API without the lookup overhead
 *   of `getOrAddService`.
 * - You are writing unit tests that construct `Service` instances directly.
 *
 * @avoidWhen
 * - You don't yet have a service instance — use {@link getOrAddService} which handles
 *   both creation and wrapping in a single call.
 *
 * @pitfalls
 * - NEVER wrap the same service instance more than once and register different handlers
 *   on each wrapper — both wrappers share the underlying `hap-nodejs` characteristic
 *   objects, so handlers registered on one wrapper overwrite those on the other.
 * - NEVER add characteristics to the service after calling `wrapService` and expect
 *   them to appear in `.characteristics` — the snapshot is taken at wrap time.
 *
 * @example
 * ```typescript
 * import { wrapService } from 'hap-fluent';
 *
 * // During configureAccessory() when restoring cached accessories
 * const rawService = accessory.getService(hap.Service.Lightbulb);
 * if (rawService) {
 *   const lightbulb = wrapService(rawService);
 *   lightbulb.onGet('on', async () => fetchState());
 * }
 * ```
 *
 * @category FluentService
 */
export function wrapService<T extends typeof Service>(service: InstanceType<T>): FluentService<T> {
  const logger = getLogger();
  // Cast once to Service to avoid InstanceType<T> & Service intersection becoming 'never'
  // (tsgo reduces the intersection to 'never' due to conflicting private members)
  const svc = service as unknown as Service;

  if (!isService(svc)) {
    logger.error({ service }, 'Invalid service object');
    throw new ValidationError('Invalid service object', {
      value: service,
      expected: 'HAP Service instance',
      actual: typeof service
    });
  }

  logger.debug(
    {
      serviceName: svc.displayName,
      uuid: svc.UUID,
      characteristicCount: svc.characteristics.length
    },
    'Wrapping service with fluent interface'
  );

  const e = {
    characteristics: Object.fromEntries(
      svc.characteristics.map((p: InstanceType<typeof Characteristic>) => {
        const camelName = camelcase(p.displayName);
        return [camelName, new FluentCharacteristic(p)];
      })
    ) as { [R in keyof FluentService<T>]: FluentCharacteristic<CharacteristicValue> }
  };

  const obj = {
    ...e,
    onGet: <K extends keyof InterfaceForService<T>>(
      key: K,
      callback: () => Promise<InterfaceForService<T>[K]>
    ) => {
      // Type assertion needed: TypeScript can't prove InterfaceForService[K] extends CharacteristicValue
      // Runtime validation happens in FluentCharacteristic
      return e.characteristics[key].onGet(
        callback as unknown as () => Promise<CharacteristicValue>
      );
    },
    onSet: <K extends keyof InterfaceForService<T>>(
      key: K,
      callback: (value: InterfaceForService<T>[K]) => Promise<void>
    ) => {
      // Type assertion needed: TypeScript can't prove CharacteristicValue extends InterfaceForService[K]
      // Runtime validation happens in FluentCharacteristic
      return e.characteristics[key].onSet(
        callback as unknown as (value: CharacteristicValue) => Promise<void>
      );
    },
    update: <K extends keyof InterfaceForService<T>>(key: K, value: InterfaceForService<T>[K]) => {
      // Type assertion needed: TypeScript can't prove InterfaceForService[K] extends CharacteristicValue
      // Runtime validation happens in FluentCharacteristic.update()
      e.characteristics[key].update(value as unknown as CharacteristicValue);
    }
  };

  for (const key in e.characteristics) {
    // Create camelCase shorthand property (e.g., "on", "brightness")
    Object.defineProperty(obj, key, {
      get: () => e.characteristics[key as keyof typeof e.characteristics].get(),
      set: (value) => e.characteristics[key as keyof typeof e.characteristics].set(value)
    });

    // Also create PascalCase shorthand property (e.g., "On", "Brightness")
    const pascalKey = key.charAt(0).toUpperCase() + key.slice(1);
    if (pascalKey !== key) {
      Object.defineProperty(obj, pascalKey, {
        get: () => e.characteristics[key as keyof typeof e.characteristics].get(),
        set: (value) => e.characteristics[key as keyof typeof e.characteristics].set(value)
      });
    }
  }

  return obj as FluentService<T>;
}
